### ISSUE TITLE
New Emoji

### ISSUE THREAD

**Issue by Prathambarve** [pandeyom331/Emojipedia#3]
I would like to add a new emoji. Can I make a PR?

**Comment by pandeyom331** [comment]
which emoji do you want to add?
I need to know it because most of the emojis are already in there, and I don't want to repeat any of them.

**Comment by Prathambarve** [comment]
I want to add the salute emoji.I have checked and its not added. @pandeyom331

**Comment by pandeyom331** [comment]
Ok, you can add it, please add it in result.json in JSON format.

**Comment by Prathambarve** [comment]
I am new to open source.I wanted to ask is it necessary to get assigned or I can just change and make a PR?

**Comment by pandeyom331** [comment]
If you are working on an issue like this one, It would be better if you get assigned, but if you directly go for a pull request (without any issue) then It's not necessary. If you have any other confusion you can ask me without any hesitation .

**Comment by Prathambarve** [comment]
@pandeyom331 Bro the problem is I have to install npm packages to run it on my pc.Is this the reason the node modules are getting updated?

**Comment by pandeyom331** [comment]
Ya this is the reason, but anyways you can delete them from your online repository and then make a PR.
